applications:
  apache2:
    charm: cs:bionic/apache2
    num_units: 1
    to: 
    - "0"
    expose: true
    options:
      enable_modules: "headers proxy_html proxy_http"
  elasticsearch:
    charm: cs:bionic/elasticsearch
    num_units: 1
    to: 
    - "4"
    options:
      apt-repository: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
  filebeat:
    charm: cs:bionic/filebeat
    options:
      install_sources: "deb https://artifacts.elastic.co/packages/6.x/apt stable main"
      kube_logs: True
  graylog:
    charm: cs:bionic/graylog
    num_units: 1
    to: 
    - "4"
    options:
      channel: "3/stable"
  mongodb:
    charm: cs:bionic/mongodb
    num_units: 1
    to: 
    - "4"
    options:
      extra_daemon_options: "--bind_ip_all"
machines:
  "0":
    constraints: tags=k8s,master
  "1":
    constraints: tags=k8s,loadB
  "2":
    constraints: tags=k8s,worker
  "3":
    constraints: tags=k8s,worker
  "4":
    constraints: tags=k8s,worker
relations:
  - ["apache2:reverseproxy", "graylog:website"]
  - ["graylog:elasticsearch", "elasticsearch:client"]
  - ["graylog:mongodb", "mongodb:database"]
  - ["filebeat:beats-host", "kubernetes-master:juju-info"]
  - ["filebeat:beats-host", "kubernetes-worker:juju-info"]
  - ["filebeat:logstash", "graylog:beats"]