series: focal
applications:
  containerd:
    charm: cs:~containers/containerd
    channel: stable
    revision: 200
    annotations:
      gui-x: "475"
      gui-y: "800"
  easyrsa:
    charm: cs:~containers/easyrsa
    channel: stable
    revision: 441
    resources:
      easyrsa: 5
    num_units: 1
    to:
    - "0"
    annotations:
      gui-x: "90"
      gui-y: "420"
  etcd:
    charm: cs:~containers/etcd
    channel: stable
    revision: 655
    resources:
      core: 0
      etcd: 3
      snapshot: 0
    num_units: 3
    to:
    - "0"
    - "1"
    - "2"
    options:
      channel: 3.4/stable
    annotations:
      gui-x: "800"
      gui-y: "420"
  flannel:
    charm: cs:~containers/flannel
    channel: stable
    revision: 619
    resources:
      flannel-amd64: 947
      flannel-arm64: 944
      flannel-s390x: 931
    annotations:
      gui-x: "475"
      gui-y: "605"
  kubeapi-load-balancer:
    charm: cs:~containers/kubeapi-load-balancer
    channel: stable
    revision: 866
    num_units: 1
    to:
    - "1"
    expose: true
    annotations:
      gui-x: "450"
      gui-y: "250"
  kubernetes-master:
    charm: cs:~containers/kubernetes-master
    channel: stable
    revision: 1106
    resources:
      cdk-addons: 0
      cni-amd64: 12
      cni-arm64: 12
      cni-s390x: 12
      core: 0
      kube-apiserver: 0
      kube-controller-manager: 0
      kube-proxy: 0
      kube-scheduler: 0
      kubectl: 0
    num_units: 1
    to:
    - "0"
    options:
      channel: 1.23/stable
    annotations:
      gui-x: "800"
      gui-y: "850"
  kubernetes-worker:
    charm: cs:~containers/kubernetes-worker
    channel: stable
    revision: 838
    resources:
      cni-amd64: 983
      cni-arm64: 974
      cni-s390x: 986
      core: 0
      kube-proxy: 0
      kubectl: 0
      kubelet: 0
    num_units: 3
    to:
    - "2"
    - "3"
    - "4"
    expose: true
    options:
      channel: 1.23/stable
    annotations:
      gui-x: "90"
      gui-y: "850"
machines:
  "0":
    constraints: tags=k8s,master
  "1":
    constraints: tags=k8s,loadB
  "2":
    constraints: tags=k8s,worker
  "3":
    constraints: tags=k8s,worker
  "4":
    constraints: tags=k8s,worker
relations:
- - kubernetes-master:loadbalancer-external
  - kubeapi-load-balancer:lb-consumers
- - kubernetes-master:loadbalancer-internal
  - kubeapi-load-balancer:lb-consumers
- - kubernetes-master:kube-control
  - kubernetes-worker:kube-control
- - kubernetes-master:certificates
  - easyrsa:client
- - etcd:certificates
  - easyrsa:client
- - kubernetes-master:etcd
  - etcd:db
- - kubernetes-worker:certificates
  - easyrsa:client
- - kubeapi-load-balancer:certificates
  - easyrsa:client
- - flannel:etcd
  - etcd:db
- - flannel:cni
  - kubernetes-master:cni
- - flannel:cni
  - kubernetes-worker:cni
- - containerd:containerd
  - kubernetes-worker:container-runtime
- - containerd:containerd
  - kubernetes-master:container-runtime