apiVersion: kubeadm.k8s.io/v1beta1
kind: InitConfiguration
bootstrapTokens:
- token: "${KUBEADM_TOKEN}"
  description: "default kubeadm bootstrap token"
  ttl: "0"
localAPIEndpoint:
  advertiseAddress: ${K8S_API_ADDVERTISE_IP_1}
  bindPort: 8443
---
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v${K8S_VERSION}
clusterName: ${K8S_CLUSTER_NAME}
controlPlaneEndpoint: ${K8S_API_ENDPOINT_INTERNAL}:6443
certificatesDir: ${LOCAL_CERTS_DIR}
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - ${K8S_API_ENDPOINT_INTERNAL}
  - ${K8S_API_ENDPOINT}

  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/
  extraArgs:
    max-requests-inflight: "1000"
    max-mutating-requests-inflight: "500"        
    default-watch-cache-size: "500"
    watch-cache-sizes: "persistentvolumeclaims#1000,persistentvolumes#1000"

controllerManager:
  # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
  extraArgs:
    deployment-controller-sync-period: "50s"
# scheduler:
#   # https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/
#   extraArgs:
#     address: 0.0.0.0



----------------
kubeadm v1.15+

apiVersion: kubeadm.k8s.io/v1beta3
bootstrapTokens:
- description: default kubeadm bootstrap token
  groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: "${KUBEADM_TOKEN}"
  ttl: 0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${K8S_API_ADDVERTISE_IP_1}
  bindPort: 8443
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  imagePullPolicy: IfNotPresent
  name: ${K8S_MASTER}
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
---
apiServer:
  certSANs:
  - ${K8S_API_ENDPOINT_INTERNAL}
  - ${K8S_API_ENDPOINT}
  extraArgs:
    default-watch-cache-size: "500"
    max-mutating-requests-inflight: "500"
    max-requests-inflight: "1000"
    watch-cache-sizes: persistentvolumeclaims#1000,persistentvolumes#1000
  timeoutForControlPlane: 4m0s
apiVersion: kubeadm.k8s.io/v1beta3
certificatesDir: ${LOCAL_CERTS_DIR}
clusterName: ${K8S_CLUSTER_NAME}
controlPlaneEndpoint: ${K8S_API_ENDPOINT_INTERNAL}:6443
controllerManager:
  extraArgs:
    deployment-controller-sync-period: 50s
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: k8s.gcr.io
kind: ClusterConfiguration
kubernetesVersion: v${K8S_VERSION}
networking:
  dnsDomain: cluster.local
  podSubnet: 10.244.0.0/16
  serviceSubnet: 10.96.0.0/12
scheduler: {}