#!/bin/bash
echo "--- Installing Docker and kube"
K8S_VERSION=${K8S_VERSION:-1.23.3}

apt-get update && apt-get install -y apt-transport-https curl zip unzip
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
deb https://apt.kubernetes.io/ kubernetes-focal main
EOF
apt-get update
apt-get install -y docker.io kubelet=${K8S_VERSION}-00 kubeadm=${K8S_VERSION}-00 kubectl=${K8S_VERSION}-00

